### ISSUE TITLE
error with vls :[TypeScript] Error: Unhandled method window/showMessageRequest

### ISSUE THREAD

**Issue by masx200** [fi3ework/vite-plugin-checker#125]
### Describe the bug

```
$npx vite serve
development serve
Pre-bundling dependencies:
  vue
  @vue/runtime-dom
  @vue/runtime-core
  element-plus
  lodash/throttle.js
(this will be run only when your dependencies or config have changed)

  vite v2.8.4 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 3065ms.

Loading Vetur in workspace path: C:\Documents\GitHub\mathjax-module-async\test

[TypeScript] Found 0 errors. Watching for file changes.

node:internal/event_target:916
  process.nextTick(() => { throw err; });
                           ^
Error: Unhandled method window/showMessageRequest
    at handleResponse (C:\Documents\GitHub\mathjax-module-async\node_modules\vscode-jsonrpc\lib\common\connection.js:477:48)
    at processMessageQueue (C:\Documents\GitHub\mathjax-module-async\node_modules\vscode-jsonrpc\lib\common\connection.js:292:17)
    at Immediate.<anonymous> (C:\Documents\GitHub\mathjax-module-async\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13)
    at processImmediate (node:internal/timers:466:21)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: -32601,
  data: undefined
}
```

### Reproduction

vite.config.ts
```ts
import vue from "@vitejs/plugin-vue";
import path from "path";
import ElementPlus from "unplugin-element-plus/vite";
import { defineConfig } from "vite";
import checker from "vite-plugin-checker";
// import VitePluginElementPlus from "vite-plugin-element-plus";
import { minifyHtml } from "vite-plugin-html";
//@ts-ignore
import virtual_plugin_for_mathjax_init from "./dist/virtual_plugin_for_mathjax_init.mjs";
const id_of_virtual_mathjax_init = "virtual:mathjax_init-js";
export default defineConfig(async ({ mode, command }) => {
    console.log(mode, command);
    // //@ts-ignore
    // const virtual_plugin_for_mathjax_init = ( //@ts-ignore
    //     await import("./dist/virtual_plugin_for_mathjax_init.mjs")
    // ).default;
    return {
        // esbuild: { drop: ["console", "debugger"] },
        build: {
            minify: "terser",
            target: "es2015",
            terserOptions: {
                output: { comments: false },
                compress: { drop_console: true, drop_debugger: true },
            },
        },
        plugins: [
            //@ts-ignore
            virtual_plugin_for_mathjax_init({ id: id_of_virtual_mathjax_init }),
            checker({ vls: true }),
            checker({ typescript: { root: path.resolve(__dirname) } }),

            ElementPlus({
                // options
            }),
            minifyHtml({ removeAttributeQuotes: false }),
            vue(),
            // VitePluginElementPlus({}),
        ],
        root: path.resolve(__dirname, "test"),
    };
});

```
package.json
```json
{
    "version": "1.4.6",
    "files": [
        "dist/index.d.ts",
        "dist/index.js",
        "dist/index.cjs"
    ],
    "dependencies": {
        "regenerator-runtime": "^0.13.9"
    },
    "publishConfig": {
        "access": "public",
        "registry": "https://registry.npmjs.org/"
    },
    "name": "@masx200/mathjax-module-async",

    "main": "dist/index.cjs",
    "module": "dist/index.js",
    "types": "dist/index.d.ts",
    "scripts": {
        "check": "tsc --noEmit",
        "build": " tsc --noEmit && npm run build1 && npm run build2",
        "build2": "rollup -c rollup.config-2.mjs",
        "build1": "rollup -c rollup.config-1.js",
        "format": " npx prettier --write */*.html */*.js  *.json */*.ts *.md *.js */*.vue *.ts",
        "dev": "npm run build1 && vite --config vite.config.ts ",
        "prod": "npm run build1 && vite build --config vite.config.ts"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "devDependencies": {
        "vite-plugin-checker": "^0.4.3",
        "vls": "^0.7.6",
        "@babel/core": "^7.14.8",
        "@babel/preset-env": "^7.14.8",
        "@masx200/serve-cli": "^1.1.6",
        "@rollup/plugin-babel": "^5.3.0",
        "@rollup/plugin-commonjs": "^19.0.2",
        "@rollup/plugin-json": "^4.1.0",
        "@rollup/plugin-node-resolve": "^13.0.4",
        "@types/lodash": "^4.14.172",
        "@vitejs/plugin-vue": "^2.2.2",
        "@vue/compiler-sfc": "^3.2.31",
        "@vue/runtime-core": "^3.2.31",
        "@vue/runtime-dom": "^3.2.31",
        "caniuse-lite": "^1.0.30001319",
        "core-js": "2",
        "element-plus": "^1.1.0-beta.12",
        "lodash": "^4.17.21",
        "node-fetch": "2",
        "prettier": "^2.3.2",
        "regenerator-runtime": "^0.13.9",
        "rollup": "^2.70.1",
        "rollup-external-modules": "^2.0.0",
        "rollup-plugin-terser": "^7.0.2",
        "rollup-plugin-ts": "^2.0.5",
        "terser": "^5.12.1",
        "tslib": "^2.3.1",
        "typescript": "^4.6.2",
        "unplugin-element-plus": "^0.3.2",
        "vite": "^2.8.4",
        "vite-plugin-html": "^2.1.0",
        "vue": "^3.2.31"
    },
    "resolutions": {
        "debug": "4.3.2",
        "object-path": "0.11.8",
        "nanoid": "3.3.1"
    },
    "directories": {
        "lib": "lib",
        "test": "test"
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/masx200/mathjax-module-async"
    },
    "packageManager": "yarn@3.2.0"
}

```

### Expected behavior

no errors

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.10 GB / 7.85 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.46)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vite-plugin-checker: ^0.4.3 => 0.4.3
```

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by masx200** [comment]
When I replaced vls with vuetsc, the error disappeared? Does this error have anything to do with typescript?


vite.config.ts
```ts
import vue from "@vitejs/plugin-vue";
import path from "path";
import ElementPlus from "unplugin-element-plus/vite";
import { defineConfig } from "vite";
import checker from "vite-plugin-checker";
// import VitePluginElementPlus from "vite-plugin-element-plus";
import { minifyHtml } from "vite-plugin-html";
//@ts-ignore
import virtual_plugin_for_mathjax_init from "./dist/virtual_plugin_for_mathjax_init.mjs";
const id_of_virtual_mathjax_init = "virtual:mathjax_init-js";
export default defineConfig(async ({ mode, command }) => {
    console.log(mode, command);
    // //@ts-ignore
    // const virtual_plugin_for_mathjax_init = ( //@ts-ignore
    //     await import("./dist/virtual_plugin_for_mathjax_init.mjs")
    // ).default;
    return {
        // esbuild: { drop: ["console", "debugger"] },
        build: {
            minify: "terser",
            target: "es2015",
            terserOptions: {
                output: { comments: false },
                compress: { drop_console: true, drop_debugger: true },
            },
        },
        plugins: [
            //@ts-ignore
            virtual_plugin_for_mathjax_init({ id: id_of_virtual_mathjax_init }),
            checker({ vueTsc:true}),
            checker({ typescript: { root: path.resolve(__dirname) } }),

            ElementPlus({
                // options
            }),
            minifyHtml({ removeAttributeQuotes: false }),
            vue(),
            // VitePluginElementPlus({}),
        ],
        root: path.resolve(__dirname, "test"),
    };
});

```

**Comment by fi3ework** [comment]
vue-tsc's watch mode for vite-plugin-check is still WIP, so not error will be shown in mode for vue-tsc

**Comment by fi3ework** [comment]
try to change

```js
 checker({ vls: true }),
            checker({ typescript: { root: path.resolve(__dirname) } }),
```

to

```js
 checker({ vls: true, typescript: { root: path.resolve(__dirname) } }),
```

**Comment by fi3ework** [comment]
vue-tsc in watch mode is supported since 0.4.4. You can drop VLS if you're using Vue3. Have a try!

**Comment by fi3ework** [comment]
Feel free to open another issue if any problem with vue-tsc watch mode in 0.4.4.
