### ISSUE TITLE
Error: Cannot find module '<projectDir>/node_modules/.pnpm/vite-plugin-checker@0.4.4_vite@2.8.6/node_modules/vite-plugin-checker/lib/checkers/vueTsc/typescript-vue-tsc/package.json'

### ISSUE THREAD

**Issue by DrJume** [fi3ework/vite-plugin-checker#129]
### Describe the bug

When enabling `vueTsc` inside vite.config.ts by setting `vueTsc: true`, this error appears when running `vite` in dev-mode.

It appears, that a `package.json` is missing inside `node_modules/vite-plugin-checker/lib/checkers/vueTsc/typescript-vue-tsc/`

The issue was fixed by downgrading to `v0.4.3`

### Reproduction

1. Install `vite-plugin-checker` with `pnpm`
2. set `vueTsc: true` inside `vite.config.js`
3. run `vite`

### Expected behavior

It should run without error.

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (8) arm64 Apple M1
    Memory: 166.08 MB / 16.00 GB
    Shell: 5.8.1 - /opt/homebrew/bin/zsh
Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
Browsers:
    Chrome: 99.0.4844.84
    Safari: 15.4
npmPackages:
    vite-plugin-checker: 0.4.4 => 0.4.4
```

### Additional context

```
node:internal/event_target:916
  process.nextTick(() => { throw err; });
                           ^
Error: Cannot find module '<projectDir>/node_modules/.pnpm/vite-plugin-checker@0.4.4_vite@2.8.6/node_modules/vite-plugin-checker/lib/checkers/vueTsc/typescript-vue-tsc/package.json'
Require stack:
- <projectDir>/node_modules/.pnpm/vite-plugin-checker@0.4.4_vite@2.8.6/node_modules/vite-plugin-checker/lib/checkers/vueTsc/prepareVueTsc.js
- <projectDir>/node_modules/.pnpm/vite-plugin-checker@0.4.4_vite@2.8.6/node_modules/vite-plugin-checker/lib/checkers/vueTsc/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at prepareVueTsc (<projectDir>/node_modules/.pnpm/vite-plugin-checker@0.4.4_vite@2.8.6/node_modules/vite-plugin-checker/lib/checkers/vueTsc/prepareVueTsc.js:44:33)
    at Object.configureServer (<projectDir>/node_modules/.pnpm/vite-plugin-checker@0.4.4_vite@2.8.6/node_modules/vite-plugin-checker/lib/checkers/vueTsc/main.js:27:71)
    at MessagePort.<anonymous> (<projectDir>/node_modules/.pnpm/vite-plugin-checker@0.4.4_vite@2.8.6/node_modules/vite-plugin-checker/lib/worker.js:56:36)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
    at Worker.[kOnExit] (node:internal/worker:267:5)
    at Worker.<computed>.onexit (node:internal/worker:198:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '<projectDir>/node_modules/.pnpm/vite-plugin-checker@0.4.4_vite@2.8.6/node_modules/vite-plugin-checker/lib/checkers/vueTsc/prepareVueTsc.js',
    '<projectDir>/node_modules/.pnpm/vite-plugin-checker@0.4.4_vite@2.8.6/node_modules/vite-plugin-checker/lib/checkers/vueTsc/main.js'
  ]
}
```

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by fi3ework** [comment]
Try deleting `node_modules` and `pnpm i` again. Does it work? Did you disabled `hoist` of pnpm in npmrc?

**Comment by DrJume** [comment]
I already tried that. I also didn't change the default pnpm settings.

**Comment by fi3ework** [comment]
Would you like to paste your package.json

**Comment by DrJume** [comment]
Issue was fixed with (probably) version 0.4.5 👍

**Comment by DrJume** [comment]
> I still get this issue on 0.4.6
> 
> ```
> node:internal/event_target:916
>   process.nextTick(() => { throw err; });
>                            ^
> Error: Cannot find module 'C:\Git\BlocPlatform\Bloc\Frontend\Bloc.Vue\node_modules\.pnpm\vite-plugin-checker@0.4.6_vite@2.9.8\node_modules\vite-plugin-checker\lib\checkers\vueTsc\typescript-vue-tsc\package.json'
> Require stack:
> - C:\Git\BlocPlatform\Bloc\Frontend\Bloc.Vue\node_modules\.pnpm\vite-plugin-checker@0.4.6_vite@2.9.8\node_modules\vite-plugin-checker\lib\checkers\vueTsc\prepareVueTsc.js     
> - C:\Git\BlocPlatform\Bloc\Frontend\Bloc.Vue\node_modules\.pnpm\vite-plugin-checker@0.4.6_vite@2.9.8\node_modules\vite-plugin-checker\lib\checkers\vueTsc\main.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at prepareVueTsc (C:\Git\BlocPlatform\Bloc\Frontend\Bloc.Vue\node_modules\.pnpm\vite-plugin-checker@0.4.6_vite@2.9.8\node_modules\vite-plugin-checker\lib\checkers\vueTsc\prepareVueTsc.js:61:29)
>     at Object.configureServer (C:\Git\BlocPlatform\Bloc\Frontend\Bloc.Vue\node_modules\.pnpm\vite-plugin-checker@0.4.6_vite@2.9.8\node_modules\vite-plugin-checker\lib\checkers\vueTsc\main.js:46:70)
>     at MessagePort.<anonymous> (C:\Git\BlocPlatform\Bloc\Frontend\Bloc.Vue\node_modules\.pnpm\vite-plugin-checker@0.4.6_vite@2.9.8\node_modules\vite-plugin-checker\lib\worker.js:75:24)
>     at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
>     at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
> Emitted 'error' event on Worker instance at:
>     at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
>     at Worker.[kOnMessage] (node:internal/worker:300:37)
>     at MessagePort.<anonymous> (node:internal/worker:201:57)
>     at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
>     at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
>     at Worker.[kOnExit] (node:internal/worker:267:5)
>     at Worker.<computed>.onexit (node:internal/worker:198:20) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     'C:\\Git\\BlocPlatform\\Bloc\\Frontend\\Bloc.Vue\\node_modules\\.pnpm\\vite-plugin-checker@0.4.6_vite@2.9.8\\node_modules\\vite-plugin-checker\\lib\\checkers\\vueTsc\\prepareVueTsc.js',
>     'C:\\Git\\BlocPlatform\\Bloc\\Frontend\\Bloc.Vue\\node_modules\\.pnpm\\vite-plugin-checker@0.4.6_vite@2.9.8\\node_modules\\vite-plugin-checker\\lib\\checkers\\vueTsc\\main.js'
>   ]
> }
> The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run dev" terminated with exit code: 1.
> ```

Me too...

**Comment by DrJume** [comment]
I could fix this issue by running `pnpm store prune` or manually deleting the whole pnpm store in `pnpm store path` and reinstalling the dependencies with `pnpm install`.

**Comment by DrJume** [comment]
It's very weird, because 1 hour ago everything was ok. 

I think a `pnpm install` in a different repo somehow deleted the `package.json` inside `typescript-vue-tsc` in my local pnpm store... So it seems to be an issue with `pnpm`?

**Comment by Miofly** [comment]
Has this problem been solved

**Comment by Miofly** [comment]
> Has this problem been solved

hello,Has this problem been solved

**Comment by fristys** [comment]
Can confirm this is still an issue

**Comment by groundfloorwebb** [comment]
I can also confirm this is still an issue. I made a fresh project with create-vue to test out this plugin, enabled the vueTsc option and immediately got the same error as everyone else.

Vite config
```
import { fileURLToPath, URL } from 'node:url';

import vue from '@vitejs/plugin-vue';
import { defineConfig } from 'vite';
import checker from 'vite-plugin-checker';

// https://vitejs.dev/config/
export default defineConfig({
	plugins: [
		checker({
			vueTsc: true,
		}),
		vue(),
	],
	resolve: {
		alias: {
			'@': fileURLToPath(new URL('./src', import.meta.url)),
		},
	},
});
```


Stack trace
```
node:internal/event_target:964
  process.nextTick(() => { throw err; });
                           ^
Error: Cannot find module '/Users/benwebb/code/create-vue-test/node_modules/vite-plugin-checker/lib/checkers/vueTsc/typescript-vue-tsc/package.json'
Require stack:
- /Users/benwebb/code/create-vue-test/node_modules/vite-plugin-checker/lib/checkers/vueTsc/prepareVueTsc.js
- /Users/benwebb/code/create-vue-test/node_modules/vite-plugin-checker/lib/checkers/vueTsc/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at prepareVueTsc (/Users/benwebb/code/create-vue-test/node_modules/vite-plugin-checker/lib/checkers/vueTsc/prepareVueTsc.js:61:29)
    at Object.configureServer (/Users/benwebb/code/create-vue-test/node_modules/vite-plugin-checker/lib/checkers/vueTsc/main.js:46:70)
    at MessagePort.<anonymous> (/Users/benwebb/code/create-vue-test/node_modules/vite-plugin-checker/lib/worker.js:75:24)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:689:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:290:10)
    at [kOnMessage] (node:internal/worker:301:37)
    at MessagePort.<anonymous> (node:internal/worker:202:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:689:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
    at [kOnExit] (node:internal/worker:268:5)
    at Worker.<computed>.onexit (node:internal/worker:199:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/benwebb/code/create-vue-test/node_modules/vite-plugin-checker/lib/checkers/vueTsc/prepareVueTsc.js',
    '/Users/benwebb/code/create-vue-test/node_modules/vite-plugin-checker/lib/checkers/vueTsc/main.js'
  ]
}
```

**Comment by groundfloorwebb** [comment]
Deleting node modules and reinstalling as described by @DrJume does seem to resolve the issue. Strange.

**Comment by DrJume** [comment]
I think it basically fails to put the package.json in the directory. A first install worked, maybe the (pnpm) upgrade sometimes deletes the package.json?

**Comment by fi3ework** [comment]
Does this issue still exists after 0.5.0? Although I'm not very clearly what cause the issue, but I added a try catch statement to prevent this.

https://github.com/fi3ework/vite-plugin-checker/blob/140f96c3d24f70e118e8397fc23aa7e41e01ee91/packages/vite-plugin-checker/src/checkers/vueTsc/prepareVueTsc.ts#L53-L66

**Comment by fi3ework** [comment]
I think it should be fixed in 0.5.0 due to https://github.com/fi3ework/vite-plugin-checker/issues/137

**Comment by z1m1n** [comment]
> I think it should be fixed in 0.5.0 from latest response in #137

Still getting this error in 0.5.1

**Comment by IlCallo** [comment]
Same here on 0.5.2 when using stylelint

```
node:internal/event_target:969
  process.nextTick(() => { throw err; });
                           ^
TypeError [Error]: (0 , import_options.default) is not a function
    at Object.configureServer (/.../node_modules/.pnpm/vite-plugin-checker@0.5.2/node_modules/vite-plugin-checker/dist/cjs/checkers/stylelint/main.js:58:60)
    at MessagePort.<anonymous> (/.../node_modules/.pnpm/vite-plugin-checker@0.5.2/node_modules/vite-plugin-checker/dist/cjs/worker.js:80:26)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:694:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:290:10)
    at Worker.[kOnMessage] (node:internal/worker:301:37)
    at MessagePort.<anonymous> (node:internal/worker:202:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:694:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
```

The mentioned import refers to `options.js`, but that file does exist, so it's the problem isn't clear

**Comment by fi3ework** [comment]
> 

This seems like not the same issue in this thread but related to https://github.com/fi3ework/vite-plugin-checker/issues as the default export is not found in CJS mode. Let's track in that issue and would like to provide a minimal re-pro?

**Comment by eleven-net-cn** [comment]
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/20358391/208068594-d4ac192c-6db8-4809-8d33-e31fefa2cbdb.png">

version: vite-plugin-checker@0.5.1
yarn v1.22.19

When I install a new package, the folder of `dist/cjs/checkers/vueTsc/typescript-vue-tsc` will be removed automatically, and then dev error.

The same as `dist/esm/...`

Error logs:

```bash
ERROR(vue-tsc)  File '/.../node_modules/vite-plugin-checker/dist/cjs/checkers/vueTsc/typescript-vue-tsc/lib/lib.dom.d.ts' not found.
```

**Comment by IlCallo** [comment]
> This seems like not the same issue in this thread but related to https://github.com/fi3ework/vite-plugin-checker/issues/184

I ignored that one since I'm using Vite 2, while that's about Vite 3
I'm gonna create a repro, I think the problem may related to the monorepo structure of my project

**Comment by daniele-orlando** [comment]
```
VITE v4.0.4  ready in 633 ms

  ➜  Local:   http://localhost:8000/
  ➜  Network: http://192.168.1.6:8000/
  ➜  press h to show help

node:internal/event_target:1013
  process.nextTick(() => { throw err; });
                           ^
Error: start < 0
    at createTextSpan (/Users/dan/example/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/typescript.js:12547:19)
    at Object.createTextSpanFromBounds (/Users/dan/example/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/typescript.js:12556:16)
    at getErrorSpanForNode (/Users/dan/example/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/typescript.js:15597:19)
    at Object.createDiagnosticForNodeFromMessageChain (/Users/dan/example/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/typescript.js:15462:20)
    at resolveExternalModule (/Users/dan/example/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/typescript.js:52379:52)
    at resolveExternalModuleNameWorker (/Users/dan/example/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/typescript.js:52301:19)
    at resolveExternalModuleName (/Users/dan/example/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/typescript.js:52296:20)
    at getSymbolAtLocation (/Users/dan/example/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/typescript.js:88409:32)
    at Object.getSymbolAtLocation (/Users/dan/example/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/typescript.js:49394:31)
    at getReferencedFilesFromImportLiteral (/Users/dan/example/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/typescript.js:122348:34)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:300:10)
    at [kOnMessage] (node:internal/worker:311:37)
    at MessagePort.<anonymous> (node:internal/worker:207:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:738:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v19.3.0
```

**Comment by isabolic** [comment]
works for me when you add  `pnpm add vue-tsc@latest typescript vite-plugin-checker  -D`  (monorepo case)

**Comment by fi3ework** [comment]
@isabolic Which re-produce method or solution works for you? 🤔

**Comment by isabolic** [comment]
@fi3ework  I had a exact error, so I run

-  `rm -rf node_modules`

- `pnpm install`

- `pnpm add --filter MONOREPO_PCK vue-tsc typescript vite-plugin-checker -D`

now `pnpm dev` has no errors

**Comment by fi3ework** [comment]
@isabolic Which version of the plugin you're using?

**Comment by isabolic** [comment]
issue still present after double check... sorry about that :)

**Comment by isabolic** [comment]
Error: EEXIST: file already exists, mkdir

**Comment by isabolic** [comment]
I think this is monorepo case, if i go into` packages/ui-components` and run `pnpm dev`/`vite dev` and go back to root repo directory, after that run again` pnpm dev` but after you add new package or update to latest  the same error appears..

**Comment by Miofly** [comment]
same error in pnpm workspace
![image](https://user-images.githubusercontent.com/42859910/233816148-42bc693e-e293-4056-81d2-05262e63c294.png)

**Comment by Montralis** [comment]
Got the same here in v0.4..8. Any update on this?

**Comment by iv-thomson** [comment]
Encountered this issue as well `vue-tsc` + `vite-plugin-checker` + `yarn 4`
the only thing that helped in my case was deleting `yarn.lock` file and running `yarn` afterwards.

```
node:internal/event_target:1033
  process.nextTick(() => { throw err; });
                           ^
Error: EROFS: read-only filesystem, mkdir '/node_modules/vite-plugin-checker/dist/cjs/checkers/vueTsc/typescript-vue-tsc'
```

**Comment by Alixhan** [comment]
`vite-plugin-checker` version 0.7.2, I got the error
``` console
  VITE v5.3.3 

error when starting dev server:
Error: Cannot find module 'vue-tsc/package.json'
Require stack:
- E:\my-workspace\xh-bms\xh-admin-frontend\node_modules\.pnpm\vite-plugin-checker@0.7.2_eslint@8.57.0_optionator@0.9.4_typescript@5.4.5_vite@5.3.3_@types+n_g2k6lq7lhxwlgneuifsug7ynae\node_modules\vite-plugin-checker\dist\esm\checkers\vueTsc\prepareVueTsc.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1186:15)
    at Function.resolve (node:internal/modules/helpers:133:19)
    at file:///E:/my-workspace/xh-bms/xh-admin-frontend/node_modules/.pnpm/vite-plugin-checker@0.7.2_eslint@8.57.0_optionator@0.9.4_typescript@5.4.5_vite@5.3.3_@types+n_g2k6lq7lhxwlgneuifsug7ynae/node_modules/vite-plugin-checker/dist/esm/checkers/vueTsc/prepareVueTsc.js:10:36
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:475:24)
    at async createCheckers (file:///E:/my-workspace/xh-bms/xh-admin-frontend/node_modules/.pnpm/vite-plugin-checker@0.7.2_eslint@8.57.0_optionator@0.9.4_typescript@5.4.5_vite@5.3.3_@types+n_g2k6lq7lhxwlgneuifsug7ynae/node_modules/vite-plugin-checker/dist/esm/main.js:31:37)
    at async config (file:///E:/my-workspace/xh-bms/xh-admin-frontend/node_modules/.pnpm/vite-plugin-checker@0.7.2_eslint@8.57.0_optionator@0.9.4_typescript@5.4.5_vite@5.3.3_@types+n_g2k6lq7lhxwlgneuifsug7ynae/node_modules/vite-plugin-checker/dist/esm/main.js:64:18)
    at async runConfigHook (file:///E:/my-workspace/xh-bms/xh-admin-frontend/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10_sass@1.77.8_terser@5.31.2/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:67013:19)
    at async resolveConfig (file:///E:/my-workspace/xh-bms/xh-admin-frontend/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10_sass@1.77.8_terser@5.31.2/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:66464:12)
    at async _createServer (file:///E:/my-workspace/xh-bms/xh-admin-frontend/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10_sass@1.77.8_terser@5.31.2/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:63048:18)
 ELIFECYCLE  Command failed with exit code 1.


18:06:11 [vite] server restart failed
```

**Comment by fi3ework** [comment]
@Alixhan Did you installed vue-tsc alongside?

**Comment by Alixhan** [comment]
@fi3ework No, I got another error after installing vue-tsc.

``` console
vite --mode development


  VITE v5.3.3  ready in 1381 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://2.0.0.1:5173/
  ➜  Network: http://172.17.112.1:5173/
  ➜  Network: http://192.168.1.134:5173/
  ➜  press h + enter to show help

node:internal/event_target:1090
  process.nextTick(() => { throw err; });
                           ^
Error [ERR_REQUIRE_ESM]: require() of ES Module E:\my-workspace\xh-bms\xh-admin-frontend\node_modules\.pnpm\vite-plugin-checker@0.7.2_eslint@8.57.0_optionator@0.9.4_typescript@5.4.5_vite@5.3.3_@types+n_uhgroegrsorsy4x5zhojfsa6s4\nod
e_modules\vite-plugin-checker\dist\esm\checkers\vueTsc\typescript-vue-tsc\lib\typescript.js from E:\my-workspace\xh-bms\xh-admin-frontend\node_modules\.pnpm\vite-plugin-checker@0.7.2_eslint@8.57.0_optionator@0.9.4_typescript@5.4.5_vite@5.3.3_@types+n_uhgroegrsorsy4x5zhojfsa6s4\node_modules\vite-plugin-checker\dist\esm\checkers\vueTsc\main.js not supported.
typescript.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename typescript.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in E:\my-workspace\xh-bms\xh-admin-fr
ontend\node_modules\.pnpm\vite-plugin-checker@0.7.2_eslint@8.57.0_optionator@0.9.4_typescript@5.4.5_vite@5.3.3_@types+n_uhgroegrsorsy4x5zhojfsa6s4\node_modules\vite-plugin-checker\package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.configureServer (file:///E:/my-workspace/xh-bms/xh-admin-frontend/node_modules/.pnpm/vite-plugin-checker@0.7.2_eslint@8.57.0_optionator@0.9.4_typescript@5.4.5_vite@5.3.3_@types+n_uhgroegrsorsy4x5zhojfsa6s4/node_modules/vite-plugin-checker/dist/esm/checkers/vueTsc/main.js:36:21) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v22.2.0
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by fi3ework** [comment]
@Alixhan You need to change your project to `type: "module"`.

**Comment by Alixhan** [comment]
![image](https://github.com/user-attachments/assets/92e3b35b-0791-4873-9c4b-62bfe1839980)
@fi3ework Yes, It is

**Comment by fi3ework** [comment]
@Alixhan Could you provide a minimal reproduction

**Comment by Alixhan** [comment]
> @Alixhan Could you provide a minimal reproduction

Thank you. I'll provide it later.

**Comment by Alixhan** [comment]
@fi3ework The demo create by latest vue .
https://stackblitz.com/edit/vitejs-vite-pqfh12?file=package.json,vite.config.ts&terminal=dev

**Comment by fi3ework** [comment]
Bumping typescript to 5.5.0 could fix the issue, I think vue-tsc requires a higher minimal version of ts now.

**Comment by so1ve** [comment]
Sorry, I don't know why typescript can't be `require`d...
