### ISSUE TITLE
Error: Cannot find module '/......./node_modules/vite-plugin-checker/lib/checkers/vueTsc/typescript-vue-tsc/package.json'

### ISSUE THREAD

**Issue by eleven-net-cn** [fi3ework/vite-plugin-checker#166]
### Describe the bug

```bash
node:internal/event_target:916
  process.nextTick(() => { throw err; });
                           ^
Error: Cannot find module '/.../node_modules/vite-plugin-checker/lib/checkers/vueTsc/typescript-vue-tsc/package.json'
Require stack:
- /.../node_modules/vite-plugin-checker/lib/checkers/vueTsc/prepareVueTsc.js
- /.../node_modules/vite-plugin-checker/lib/checkers/vueTsc/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at prepareVueTsc (/.../node_modules/vite-plugin-checker/lib/checkers/vueTsc/prepareVueTsc.js:61:29)
    at Object.configureServer (/.../node_modules/vite-plugin-checker/lib/checkers/vueTsc/main.js:46:70)
    at MessagePort.<anonymous> (/.../node_modules/vite-plugin-checker/lib/worker.js:75:24)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/.../node_modules/vite-plugin-checker/lib/checkers/vueTsc/prepareVueTsc.js',
    '/.../node_modules/vite-plugin-checker/lib/checkers/vueTsc/main.js'
  ]
}
```

package.json does not exist in the directoryf

![Uploading image.png…]()

### Reproduction

...

### Expected behavior

...

### System Info

```shell
node v16.14.0
```

### Additional context

...

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by stefusilviu** [comment]
Duplicate of #129 ?
