### ISSUE TITLE
vue-tsc v1.0.14 throws with ``

### ISSUE THREAD

**Issue by cexbrayat** [fi3ework/vite-plugin-checker#193]
### Describe the bug

Volar v1.0.14 has just been released and there are some changes,
in particular https://github.com/johnsoncodehk/volar/commit/e5f7b230717a06988cff71df1ae4ffaaa24da166#diff-5270d6425aa3f2991337ef48a11f7e996d30adf2618e5c2428077ff2c8a8f149
that renames `proxy.ts` to `index.ts`.

Using vite-plugin-checker with vue-tsc v1.0.14 throws:

```
Error: Cannot find module 'vue-tsc/out/proxy'
Require stack:
- /home/circleci/redacted/node_modules/vite-plugin-checker/dist/cjs/checkers/vueTsc/prepareVueTsc.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at Object.<anonymous> (/home/circleci/redacted/node_modules/vite-plugin-checker/dist/cjs/checkers/vueTsc/prepareVueTsc.js:39:28)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/circleci/redacted/node_modules/vite-plugin-checker/dist/cjs/checkers/vueTsc/main.js:42:28) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/circleci/redacted/node_modules/vite-plugin-checker/dist/cjs/checkers/vueTsc/prepareVueTsc.js'
  ]
}
```

### Reproduction

```
npm create vue vue-tsc-v1.0.14 -- --typescript
cd vue-tsc-v1.0.14
npm i
npm i --save-dev --save-exact vite-plugin-checker
```

Enables vite-plugin checker for vue-tsc:
```ts
import checker from 'vite-plugin-checker'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(), checker({
    vueTsc: true
  })],
```

then start:
```
npm run dev
```

Throws:
```
> vue-tsc-v1.0.14@0.0.0 dev
> vite

error when starting dev server:
Error: Cannot find module 'vue-tsc/out/proxy'
Require stack:
- /Users/cedric/Code/temp/vue-tsc-v1.0.14/node_modules/vite-plugin-checker/dist/cjs/checkers/vueTsc/prepareVueTsc.js
```

### Expected behavior

Should start without error

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 7.86 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.volta/tools/image/node/16.17.0/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.19.3 - ~/.volta/tools/image/npm/8.19.3/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0.1
    Safari: 16.2
  npmPackages:
    vite-plugin-checker: 0.5.2 => 0.5.2
```

### Additional context

This only breaks with vue-tsc v1.0.14, reverting to v1.0.13 works

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by theoephraim** [comment]
@cexbrayat @fi3ework 

I've just upgraded some dependencies and still seeing this issue.
I created a brand new project as well to confirm...

Reverting vue-tsc to 1.0.13, does resolve it for now, but it seems this issue is not quite fixed.

To reproduce
- set up a new vue project using vite started `npm create vite@latest`
- install vite-plugin-checker and add to vite config

```
error when starting dev server:
Error: Cannot find module 'vue-tsc/out/proxy'
Require stack:
- /.../node_modules/.pnpm/vite-plugin-checker@0.5.1_vwvfc4ezh6jlf6pa67auy3eulu/node_modules/vite-plugin-checker/dist/esm/checkers/vueTsc/prepareVueTsc.js
```

**Comment by fi3ework** [comment]
@cexbrayat In vue-tsc 1.1.0, `vue-tsc/out/proxy` has been removed. It's been fixed in https://github.com/fi3ework/vite-plugin-checker/commit/538a0d95900f3eacac4e02ebc1be9311712e4a07 and released in 0.5.3. Bump the version should fix all.

**Comment by theoephraim** [comment]
I could have sworn I was on the latest versions of everything. Apologies for the noise!

**Comment by ouyangzhigang** [comment]
ERROR  Cannot start nuxt:  Cannot find module 'vue-tsc/out/proxy'                                            15:54:39
Require stack:
- D:\private\nuxt-app-workflow\node_modules\vite-plugin-checker\dist\esm\checkers\vueTsc\prepareVueTsc.js
