### ISSUE TITLE
Crashes in typescript with "RangeError [Error]: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by panstromek** [fi3ework/vite-plugin-checker#243]
### Describe the bug

I keep hitting this all the time, it happens multiple times per hour, crashes the whole Vite process and I have to restart it. 

```
node:internal/event_target:1011
  process.nextTick(() => { throw err; });
                           ^
RangeError [Error]: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at toFileNameLowerCase (D:\<...project_folder>\analyzer\node_modules\typescript\lib\typescript.js:1190:48)
    at toPath (D:\<...project_folder>\analyzer\node_modules\typescript\lib\typescript.js:6817:12)
    at Object.getOrCreateSourceFile (D:\<...project_folder>\analyzer\node_modules\typescript\lib\typescript.js:139869:54)
    at D:\<...project_folder>\analyzer\node_modules\typescript\lib\typescript.js:139796:44
    at Object.getSourceFileWithCache [as getSourceFile] (D:\<...project_folder>\analyzer\node_modules\typescript\lib\typescript.js:116025:26)
    at findSourceFileWorker (D:\<...project_folder>\analyzer\node_modules\typescript\lib\typescript.js:118297:25)
    at findSourceFile (D:\<...project_folder>\analyzer\node_modules\typescript\lib\typescript.js:118217:22)
    at processImportedModules (D:\<...project_folder>\analyzer\node_modules\typescript\lib\typescript.js:118646:13)
    at findSourceFileWorker (D:\<...project_folder>\analyzer\node_modules\typescript\lib\typescript.js:118352:9)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:298:10)
    at Worker.[kOnMessage] (node:internal/worker:309:37)
    at MessagePort.<anonymous> (node:internal/worker:205:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
error Command failed with exit code 1.

```

### Reproduction

1. create new vite project with Vue and typescript
2. add checker config:
```typescript
export default defineConfig({
    plugins: [
        vue(),
        checker({
            vueTsc: true,
            overlay:false,
            enableBuild:true,
            eslint: {
                lintCommand: 'eslint "./src/**/*.{ts,vue}"'
            }
        }),
    ]
})
```
3. Run vite
4. edit some code (usually happens after multiple iterations of edit-save-check)

### Expected behavior

I don't know how much is this just typescript being typescript, I have performance problems with it in other projects as well, but I'd expect the checker to gracefully restart the worker in this case (that's what I  do manually anyway).

Maybe there's something going on with the checker, though (is there something recursive happening when you edit files?)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 8.81 GB / 31.87 GB
  Binaries:
    Node: 16.18.1 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 113.0.5672.127
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.43)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vite-plugin-checker: ^0.6.0 => 0.6.0
```

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by fi3ework** [comment]
What's the version of vue-tsc and typescript in your project?

**Comment by panstromek** [comment]
@fi3ework 

```
vue-tsc      1.6.5
typescript  5.1.3
```

I'll try to update today, to see if it helps

**Comment by panstromek** [comment]
I upgraded to `typescript@5.1.3`, `vue-tsc@1.8.1` and `vite-plugin-checker@0.6.1`. I spent last 1-2 hours developing and I haven't seen a crash so far, so it seems like the problem might be fixed. `vue-tsc` had some memory usage improvements in release notes, maybe that's it?

I'll keep an eye on this and close the issue if I don't encounter the crash again.

**Comment by fi3ework** [comment]
Based on the description, it could be an issue of vue-tsc with some specific typescript version (Not confirmed, just a guess 🤔). I'll close this issue for now and feel free to reopen it if you encounter it again!

By the way, you could verify this issue by running `vue-tsc --noEmit --watch` as vite-plugin-checker is only some kind of binding of the checker and the UI.
