### ISSUE TITLE
ESLint doesn't work with flat config

### ISSUE THREAD

**Issue by sndrrth** [fi3ework/vite-plugin-checker#244]
### Describe the bug

ESLint introduced a new configuration format `eslint.config.js` (flat config). With the new format, an error is thrown when starting the application:

```
node:internal/event_target:1012
  process.nextTick(() => { throw err; });
                           ^
Error: No ESLint configuration found in \src\stories\_utils\docs.
    at CascadingConfigArrayFactory._finalizeConfigArray (\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3977:19)
    at CascadingConfigArrayFactory.getConfigArrayForFile (\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3768:21)
    at FileEnumerator._iterateFilesRecursive (\node_modules\eslint\lib\cli-engine\file-enumerator.js:473:52)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator._iterateFilesRecursive (\node_modules\eslint\lib\cli-engine\file-enumerator.js:495:33)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator._iterateFilesRecursive (\node_modules\eslint\lib\cli-engine\file-enumerator.js:495:33)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator._iterateFilesRecursive (\node_modules\eslint\lib\cli-engine\file-enumerator.js:495:33)
    at _iterateFilesRecursive.next (<anonymous>)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:300:10)
    at [kOnMessage] (node:internal/worker:311:37)
    at MessagePort.<anonymous> (node:internal/worker:212:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:737:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
    at [kOnExit] (node:internal/worker:278:5)
    at Worker.<computed>.onexit (node:internal/worker:209:20) {
  messageTemplate: 'no-config-found',
  messageData: {
    directoryPath: 'src\\stories\\_utils\\docs'
  }
```

Running ESLint directly via CLI works with the new config. The checker plugin worked properly before migrating to the new ESLint config.

### Reproduction

1. Migrate the ESLint config to `eslint.config.js`
2. Run `vite` with configured `vite-plugin-checker`

### Expected behavior

ESLint should run without an error and the `eslint.config.js` file should be used.

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 34.69 GB / 63.70 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.43)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vite-plugin-checker: 0.6.0 => 0.6.0
```

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by sndrrth** [comment]
The `ESLint` class used by this plugin doesn't support the new flat config. For the flat config the `FlatESLint` class must be used which is only exported via `eslint/use-at-your-own-risk` entrypoint: https://eslint.org/blog/2022/08/new-config-system-part-3/#using-flat-config-with-the-eslint-class

**Comment by Swiftwork** [comment]
Ran into this exact issue today as well.

**Comment by zhoushengdong** [comment]
It happened to me.

Is this problem solved?

**Comment by phoenix-oes** [comment]
Anyone from the future finding your way to this closed issue through a search, yes, it has been solved. Update your vite-plugin-checker:

```ts
            eslint: {
              lintCommand: 'eslint .',
              useFlatConfig: true,
            },
```
