### ISSUE TITLE
Compatibility with vue-tsc@2.1

### ISSUE THREAD

**Issue by daniluk4000** [fi3ework/vite-plugin-checker#397]
### Is your feature request related to a problem? Please describe.

While https://github.com/fi3ework/vite-plugin-checker/pull/395 is a fix for updating vue-tsc, it seems like Vue 3.5 broke things for us, and when Volar patch comes out, we will be blocked for updating to Vue 3.5.

### Describe the solution you'd like

Update to last vue-tsc version and fix issues we have with it due to internal API changed

### Describe alternatives you've considered

Stay on Vue <3.5 with locked vue-tsc

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Read the [Contributing Guidelines](https://github.com/fi3ework/vite-plugin-checker/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by myBoris** [comment]
node:internal/event_target:1094
  process.nextTick(() => { throw err; });
                           ^
TypeError [Error]: pluginContext.vueCompilerOptions.plugins is not iterable
    at createPlugins (XXX\node_modules\@vue\language-core\lib\plugins.js:48:45)
    at Object.createVueLanguagePlugin (XXX\node_modules\@vue\language-core\lib\languagePlugin.js:52:49)
    at exports.getLanguagePlugins (XXX\node_modules\vite-plugin-checker\dist\cjs\checkers\vueTsc\languagePlugins.cjs:30:33)
    at Object.apply (XXX\node_modules\@volar\typescript\lib\node\proxyCreateProgram.js:50:33)
    at getBuilderCreationParameters (XXX\node_modules\vite-plugin-checker\dist\cjs\checkers\vueTsc\typescript-vue-tsc\lib\typescript.js:128533:18)
    at createSemanticDiagnosticsBuilderProgram (XXX\node_modules\vite-plugin-checker\dist\cjs\checkers\vueTsc\typescript-vue-tsc\lib\typescript.js:129027:74)
    at createNewProgram (XXX\node_modules\vite-plugin-checker\dist\cjs\checkers\vueTsc\typescript-vue-tsc\lib\typescript.js:131080:22)
    at synchronizeProgram (XXX\node_modules\vite-plugin-checker\dist\cjs\checkers\vueTsc\typescript-vue-tsc\lib\typescript.js:131054:7)
    at Object.createWatchProgram (XXX\node_modules\vite-plugin-checker\dist\cjs\checkers\vueTsc\typescript-vue-tsc\lib\typescript.js:130960:3)
    at Object.configureServer (XXX\node_modules\vite-plugin-checker\dist\cjs\checkers\vueTsc\main.js:128:13)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
    at [kOnExit] (node:internal/worker:304:5)
    at Worker.<computed>.onexit (node:internal/worker:229:20)

Node.js v20.16.0
