### ISSUE TITLE
Exception when running dev

### ISSUE THREAD

**Issue by fgblomqvist** [fi3ework/vite-plugin-checker#47]
```
(node:15198) UnhandledPromiseRejectionWarning: TypeError: _chalk.constructor is not a constructor
    at getChalk (/myapp/node_modules/@babel/highlight/lib/index.js:102:31)
    at Object.codeFrameColumns (/myapp/node_modules/@babel/code-frame/lib/index.js:92:41)
    at createFrame (/myapp/node_modules/vite-plugin-checker/lib/logger.js:76:32)
    at /myapp/node_modules/vite-plugin-checker/lib/logger.js:225:27
    at Array.map (<anonymous>)
    at Object.normalizeEslintDiagnostic (/myapp/node_modules/vite-plugin-checker/lib/logger.js:201:10)
    at /myapp/node_modules/vite-plugin-checker/lib/checkers/eslint/main.js:56:72
    at Array.map (<anonymous>)
    at Object.<anonymous> (/myapp/node_modules/vite-plugin-checker/lib/checkers/eslint/main.js:56:52)
    at Generator.next (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15198) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

events.js:292
      throw er; // Unhandled 'error' event
      ^
TypeError [Error]: _chalk.constructor is not a constructor
    at getChalk (/myapp/node_modules/@babel/highlight/lib/index.js:102:31)
    at Object.codeFrameColumns (/myapp/node_modules/@babel/code-frame/lib/index.js:92:41)
    at createFrame (/myapp/node_modules/vite-plugin-checker/lib/logger.js:76:32)
    at Object.normalizeTsDiagnostic (/myapp/node_modules/vite-plugin-checker/lib/logger.js:109:21)
    at reportDiagnostic (/myapp/node_modules/vite-plugin-checker/lib/checkers/typescript/main.js:41:55)
    at Array.forEach (<anonymous>)
    at emitFilesAndReportErrors (/myapp/node_modules/typescript/lib/typescript.js:115397:21)
    at Object.result.afterProgramCreate (/myapp/node_modules/typescript/lib/typescript.js:115574:13)
    at synchronizeProgram (/myapp/node_modules/typescript/lib/typescript.js:115864:22)
    at Object.createWatchProgram (/myapp/node_modules/typescript/lib/typescript.js:115788:9)
Emitted 'error' event on process instance at:
    at emitUnhandledRejectionOrErr (internal/event_target.js:545:11)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:358:9)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)
    at Worker.[kOnExit] (internal/worker.js:233:5)
    at Worker.<computed>.onexit (internal/worker.js:174:20)

Process finished with exit code 1
```
Let me know what kind of information would be helpful here.

**Comment by fi3ework** [comment]
Could you run this command in your project and give me some basic information for debugging

```bash
npx envinfo --system --npmPackages vite-plugin-checker --binaries --browsers
```

**Comment by fgblomqvist** [comment]
```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 38.75 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    npm: 7.11.2 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Firefox: 89.0.2
    Safari: 14.0
  npmPackages:
    vite-plugin-checker: 0.3.2 => 0.3.2
```

**Comment by fgblomqvist** [comment]
Did some googling and someone said to delete the node_modules folder. Tried that + npm install and now the plugin works 🤷
